### ISSUE TITLE
Does VA Confirmation API use DMDC for source?

### ISSUE THREAD

**Issue by ArvindKos** [department-of-veterans-affairs/developer-portal#1170]
Hi,

I am trying to test VA Confirmation API for veteran info, does VA Confirmation API use DMDC for verification source or it has own data source?

**Comment by gileswells** [comment]
Hello,

Sorry this issues thread isn't better labeled / better linked to our support team. I'll put something in our backlog to address this so that future questions reach the right team directly.

Please repost your question to our [Developer Portal Support form](https://dev-developer.va.gov/support/contact-us) and they will be better able to assist you.

Thank you.
